### ISSUE TITLE
Usage of groups.

### ISSUE THREAD

**Issue by mndmr** [chuot/rdio-scanner#10]
Would be nice to be able to filter transmissions based off of group. When selecting talkgroups have them sorted by the groups. That way all audio from a system could be piped in to rdio-scanner and I can decide what groups I want to listen to.

**Comment by chuot** [comment]
Thanks for your suggestion. So I invested some time this morning to produce a new version which includes this new functionality. I hope it will meet your expectations.

Happy rdio scanning!
