### ISSUE TITLE
Frequency Does not update in IOS app but is correct on web gui

### ISSUE THREAD

**Issue by tdduarte** [chuot/rdio-scanner#103]
When adding fake frequency into rdio admin page (had to use for voxcall as the frequency entered doesn't seem to push to rdio) it updates the web gui but does not update on the ios app. 
![image](https://user-images.githubusercontent.com/24261554/150067273-6d24def8-928c-4aaf-9733-3368de8f6ed5.jpeg)

**Comment by tdduarte** [comment]
![image](https://user-images.githubusercontent.com/24261554/150067431-2a42d208-7e4d-4602-a0cb-106f38a78533.jpeg)

**Comment by chuot** [comment]
Please confirm that you've entered the frequency at the dirwatch level, or was it in the talkgroup definition?

**Comment by tdduarte** [comment]
This is in the talkgroup definition as its an api from voxcall

**Comment by chuot** [comment]
Thanks, it will be fixed in the next release of the native app.

**Comment by tdduarte** [comment]
Great!  Thank you for all your work on this project!
