### ISSUE TITLE
Assign System/Talkgroup from Incoming Frequency

### ISSUE THREAD

**Issue by nightwolfgroup** [chuot/rdio-scanner#118]
I have been messing with some Python scripts to append the system/talkgroup to a file coming from rtl_airband in scan mode, then have the script move it to be ingested to rdio-scanner.

This would be great for those utilizing rtl_airband if the system and talkgroup could be assigned to the call within rdio-scanner based on the frequency tagged to the file from rtl_airband.

As far as I know, if running rtl_airband in scan mode, you can set a mask but that will be applied to all frequencies coming from that device (the only change being date/time and frequency).

This could be a future enhancement or there may be a better way to accomplish this some other way.

Thanks!

**Comment by Brubeck48** [comment]
Yeah! I'm looking for the same feature. Now since Rdio-scanner updated to v.6.1.8 we can specify TGHZ. It could be a good idea to find a way how to specify also different Systems with rtl_airband scan mode.
