### ISSUE TITLE
Add number of listeners field to main screen.

### ISSUE THREAD

**Issue by photounit** [chuot/rdio-scanner#125]
Would it be possible to add a number of listeners field to the main screen?

**Comment by jtetterton2** [comment]
I second this, I opened another enhancement request then saw this one! I will go figure out if I can delete my request.

Thanks for considering this option!

**Comment by chuot** [comment]
I will add something in v6.2 in regards to this enhancement request.

**Comment by chuot** [comment]
Added in v6.2
