### ISSUE TITLE
v6.1.10 still deleting all TGs in System

### ISSUE THREAD

**Issue by JayManCanada6014** [chuot/rdio-scanner#127]
Brand new copy of 6.1.10.
Goto my 5.2.9 and turn off all the auto-populates and export the config
Import config to 6.1.10,  all systems and TGs are there, press save 
And all Talkgroups start getting deleted, repopulated by the TR .csv file but only temporarily but delete just as fast.

Same issues I've been having since the change of backend programming from v5 to v6.

**Comment by chuot** [comment]
Fixed in v6.1.11
