### ISSUE TITLE
UID Aliases

### ISSUE THREAD

**Issue by mdozier9** [chuot/rdio-scanner#16]
Has the alias functionality changed from 3.0 to 3.1?  3.1 does not appear to support the api/trunk-recorder-alias-upload push ("Cannot POST /api/trunk-recorder-alias-upload"), nor does it appear to look at the aliases data in the systems table.  Is there a new method for doing friendly alias names for UIDs?

**Comment by chuot** [comment]
Indeed. It got lost in the previous code refactoring. I will commit a fix tomorrow.

Thanks for the report.

**Comment by mdozier9** [comment]
Lol..thanks for the sanity check Chrystian.  I was pulling my hair out trying to figure out what I was doing wrong.

**Comment by mdozier9** [comment]
Confirmed.  Both the upload and db alias read are working.  Thanks!
