### ISSUE TITLE
Call Search page selection grey out after starting play back

### ISSUE THREAD

**Issue by infecticide** [chuot/rdio-scanner#161]
rdio-scanner: 6.2.4
OS: Ubuntu 21.04

Steps to reproduce:
Load main screen
Select Search Call
The page selector should be working
Play a call
The page selector is now greyed out

**Comment by chuot** [comment]
This is normal behavior, it's called `playback mode` where it will play calls in search list order. This is useful if you want to replay an event from the past. You can only start in playback mode if the livefeed button is off (red). In playback mode, the search filters and the paginator are disabled. Note that the calls will be played one after the other in the order of the search list. The search list will also change pages to follow the current playing call. To stop playback mode, press the stop button on the currently playing call or deactivate the livefeed button, which is orange in playback mode.
