### ISSUE TITLE
Increase searching speed (recommendation)

### ISSUE THREAD

**Issue by kcwebby** [chuot/rdio-scanner#165]
Perhaps moving the blob audio data to a linked table, would speed up searches in the calls table?
change audio to audio_id and create a new rdio_audio table with ID and Audio blob for linking?

**Comment by chuot** [comment]
Searching from the search panel is quite fast and does not warrant a change in database structure at this time.

**Comment by gisforgirard** [comment]
> Searching from the search panel is quite fast and does not warrant a change in database structure at this time.

![Screenshot from 2023-02-03 19-10-15](https://user-images.githubusercontent.com/17693551/216733473-411b2a2a-bf2c-4ba7-ae86-d69614c1d63f.png)
sure, maybe for you .... haha
