### ISSUE TITLE
DB and App Don't Update When DB has External Changes Made

### ISSUE THREAD

**Issue by josephdambrosio** [chuot/rdio-scanner#167]
Using MySQL as the DB, when I make changes directly to the DB file for the Access table the records do show in the DB, but can't log into the app with those credentials until restarting the instance of Rdio Scanner and then the records copy over into the webGUI and allow for access.  Am I just missing something here or is there a bug with checking the DB for updates?

**Comment by chuot** [comment]
It works as expected. Everything is kept in memory for performance reasons. When a change is made through the admin dashboard, it is persisted to the database. Pushing directly to the database is neither recommended nor supported.
