### ISSUE TITLE
Correct way to upload talkgroups?

### ISSUE THREAD

**Issue by mjmikolay** [chuot/rdio-scanner#17]
Perhaps since it is the late hour and/or my novice status with Ubuntu creating and running scripts but I can't for the life of me get my three systems talkgroups uploaded. I've tried everything I can think of and running it from everywhere. Can you kindly guide me as to how or where I should be running the upload-systems.sh script?

Everything else appears to be working and files are being successfully uploaded into the database. I just don't have the talkgroups, etc.

Thank you for an amazing program! Can't wait to fully use it.

**Comment by chuot** [comment]
Now that version 4.0 is out, configuring systems/talkgroups is done through a config.json file. See the `docs/config.md` file for instructions.

**Comment by mjmikolay** [comment]
Thank you!
