### ISSUE TITLE
Program stops reading in audio files

### ISSUE THREAD

**Issue by infusopharm** [chuot/rdio-scanner#182]
Running on Windows computer. sdrtrunk working well. For some reason rdio-scan will stop reading in files generated by sdrtrunk. Seems to happen daily. Restart program and all the backed up files get read in with no issues. Not sure if any configuration I may need to address on my end?
Thanks
Steven

**Comment by infusopharm** [comment]
Just started experimenting with the program.  I will definately work to provide as much info as I can to determine the issue. Preliminary believe to occur shortly after make changes in the admin page.

**Comment by chuot** [comment]
dirwatch seems to be buggy, I'm in the process of rewritting it a little bit. Keep an eye on the upcoming release.

**Comment by infusopharm** [comment]
Great.

**Comment by chuot** [comment]
try with v6.3.1 to see if it solves your issue

**Comment by infusopharm** [comment]
Ran new file. Only runs for a few minutes and then program closes
completely.
Steven

**Comment by infusopharm** [comment]
I saw you updated. Will try later today. Much appreciated.
