### ISSUE TITLE
Nginx Reverse Proxy

### ISSUE THREAD

**Issue by davbay1** [chuot/rdio-scanner#184]
Hi everyone,

Has anyone been able to get Rdio-Scanner to work through a Nginx reverse proxy? When I am on lan and go to the web ui via the ip, it works great. However, when I try to access using the domain name through the reverse proxy, I see the web ui but it says no link and I am unable to go any further.

I appreciate any help.

**Comment by JayManCanada6014** [comment]
You need to enable WebSockets Support on your proxy.

**Comment by chuot** [comment]
Please don't post questions as issues, use the discussions for that.
