### ISSUE TITLE
Settings in options not being read from mysql/mariadb at startup

### ISSUE THREAD

**Issue by kb2ear** [chuot/rdio-scanner#190]
discovered that anything you set in the options like: Disable Audio Conversion, Show Listeners Count to be specific, are not being held across restarts of the software going back to at least 6.3.2. I can set them, they work until I restart the software, then they no longer show as turned on and are not working.  If I do a export config the json shows them as true.

**Comment by kb2ear** [comment]
export before restart:
  "options": {
    "afsSystems": "",
    "autoPopulate": true,
    "dimmerDelay": 5000,
    "disableAudioConversion": true,
    "disableDuplicateDetection": false,
    "duplicateDetectionTimeFrame": 500,
    "keypadBeeps": "uniden",
    "maxClients": 200,
    "pruneDays": 7,
    "searchPatchedTalkgroups": false,
    "showListenersCount": true,
    "sortTalkgroups": false,
    "tagsToggle": false
  },
```
export after restart:
```
  "options": {
    "afsSystems": "",
    "autoPopulate": true,
    "dimmerDelay": 5000,
    "disableAudioConversion": false,
    "disableDuplicateDetection": false,
    "duplicateDetectionTimeFrame": 500,
    "keypadBeeps": "uniden",
    "maxClients": 200,
    "pruneDays": 7,
    "searchPatchedTalkgroups": false,
    "showListenersCount": false,
    "sortTalkgroups": false,
    "tagsToggle": false
  },
```
in SQL after restart:
```
{
   "pruneDays":7,
   "afsSystems":"",
   "maxClients":200,
   "tagsToggle":false,
   "dimmerDelay":5000,
   "keypadBeeps":"uniden",
   "autoPopulate":true,
   "sortTalkgroups":false,
   "showListenersCount":true,
   "disableAudioConversion":true,
   "searchPatchedTalkgroups":false,
   "disableDuplicateDetection":false,
   "duplicateDetectionTimeFrame":500
}
```

**Comment by kb2ear** [comment]
same issue on mariadb

**Comment by chuot** [comment]
it's actually the same code. Please let me know if v6.3.5 fixed it

**Comment by kb2ear** [comment]
I seems to be fixed in 6.3.5 thanks
