### ISSUE TITLE
Choosing log level under Logs in the admin page throws http failure response

### ISSUE THREAD

**Issue by infecticide** [chuot/rdio-scanner#193]
Error:
Http failure response for $URL/api/admin/logs: 417 Expectation Failed

Steps to reproduce:
- Authenticate to /admin page
- Click Logs
- Select a log level from the drop down in the bottom right

Using MariaDB for SQL backend.

**Comment by infecticide** [comment]
Changing to SQLite DB backend solves this issue.   I do want to continue using MySQL however.

**Comment by chuot** [comment]
You should be good to go with v6.4.0

**Comment by chuot** [comment]
Old logs prior to the fix wouldn't appear, but new ones did. So it looks fixed to me.
