### ISSUE TITLE
Enhancement - In continuation of #186 Highlight the Replayed Call

### ISSUE THREAD

**Issue by noamlivne** [chuot/rdio-scanner#196]
In continuation of https://github.com/chuot/rdio-scanner/issues/186,
Please highlight the Replayed Call so users will not be confused about the current call being played.
Thank you very much!

**Comment by chuot** [comment]
Try with v6.4.0. Native hasn't been yet updated as I'm tracking down the audio issue.

**Comment by noamlivne** [comment]
Excellent. Thank you very much!
