### ISSUE TITLE
Hold TG turns off all selected TGs in Select TG

### ISSUE THREAD

**Issue by tadscottsmith** [chuot/rdio-scanner#200]
Occasionally, when I use the **HOLD TG** button to lock on a channel, and then later click the **HOLD TG** to resume normal listening, all of my talk groups are turned off, and my preferences of which to listen to our lost. This does not happen every time. Is there some logs that I can look into to try and figure out why?

**Comment by chuot** [comment]
Indeed. It looks like this happens when autopopulate occurs. Whill fix in the next patch release. Thanks for reporting it.

**Comment by chuot** [comment]
Fixed
