### ISSUE TITLE
[feature]  Volume Control on Scanner?

### ISSUE THREAD

**Issue by kcwebby** [chuot/rdio-scanner#202]
Is it possible to incorporate a volume control into the app, and web app?

**Comment by chuot** [comment]
Is this because the latest loudnorm audio filter sounds too high? The next version will have an option to disable it anyway.

**Comment by kcwebby** [comment]
No I think this is just for those people who might have multiple audio things going on, and want to be able to independently control the volume of the scanner with misc other audio sources on the computer.  Windows by default will control all "Chrome" sources as one if your open the Volume Mixer.  So having a volume limit switch on the scanner would provide more granularity to the end user.
This is a request of a couple of our end users, and something that I agree with, but don't deem critical, so I am mentioning for future enhancement more than a "fix".  
Thanks.
