### ISSUE TITLE
Enhancement? Control archive access on user level

### ISSUE THREAD

**Issue by infusopharm** [chuot/rdio-scanner#208]
Possibly would go against your design for this cool program but thought I would ask. Any option to turn off  an user to be able to listen back to archieves. Dont want to add fuel to the fire with local agencies all over the country swiching to encryption. Current state gives everyone this ability and ease of sharing select audio all over social concerns me.  Just a thought. Thanks.

**Comment by chuot** [comment]
Feel free to open a discussion on the topic.

Closing this for now.
