### ISSUE TITLE
Groups Missing from Select TG Screen

### ISSUE THREAD

**Issue by tadscottsmith** [chuot/rdio-scanner#215]
Something happened to my DB, and no matter what I do, I can no longer get the talk groups to display by groups in the "Select TG" screen. This seemed to happen out of the blue on V6.2.4, so I updated to current and version, wiped everything, and tried to reimport the config as well as reimport from CSV. I can not get the "Groups" to show in select TG even though they appear to be recognized by the DB.

![TG](https://user-images.githubusercontent.com/78445808/173491183-8dc39233-e5b7-4d55-82e3-7b35dec915f6.JPG)
![Groups](https://user-images.githubusercontent.com/78445808/173491191-06a607bc-2533-4870-bb3a-f3121bf1ec45.JPG)
![Select](https://user-images.githubusercontent.com/78445808/173491196-7a383561-34fd-4600-b5ad-8d60672bc858.JPG)
.

**Comment by chuot** [comment]
Groups will only appear if they are linked to a talkgroup that the access code gives access to it.

Do you use access codes?

**Comment by tadscottsmith** [comment]
I apologize, I thought that the Select TG had the talk groups separated and sorted by the group name, but it seems that hasn’t been the case. I will close.
