### ISSUE TITLE
Unable to download files via Andorid (Premium version)

### ISSUE THREAD

**Issue by LoveScanner** [chuot/rdio-scanner#216]
i use andorid 12 Ui 4.1 know 3.8 

I can not download recordings through a premium version,
It is important to note that I have given permission for file permissions
 
I press the download button and nothing happens - maybe it's going down in the background? In which directory should I look for it?

On this occasion I will ask / Suggestions
1. Where are the recordings physically stored?
2. It is possible to display the site number or name (via sdr-trunk) even instead of speech frequency - will help me a lot
3. Would be nice if there would be an option of Export Talkgroups or at least a csv format for example,
Because there are systems that are not in RR (outside of America) and I do not even have the format of the file (maybe you have an example?)
4. Would be nice if under the option "Keypad Beep Style Provide audio feedback when pressing buttons"
There will be a No Sound option
5. Sometimes I'm under SEARCH CALL I can not hear old recordings it does nothing, only after a restart to the application the problem works out
6. It would be nice when I hear an old recording that it will continue to play me the recordings in sequence and I do not have to click play one by one
7. If my Prune Days stood at 7 days and I have now updated it to 1 When will it physically erase the old ones only at 12 at night?

**Comment by chuot** [comment]
The first time you try to download, you should have been prompted to allow the storage permission to the app. It should ask again if you've answered deny. But on some android devices, you can also choose deny and do not ask again. If it's the case, you won't be prompted anymore and that could lead to the symptom you're describing. Go see in the app persmissions if it as storage permission or not; it should.

On android, calls are saved in the Download folder of the internal storage.

I have added a new error message to the upcoming version of the native app which will popup if the app doesn't have storage permission.

The audio issue where it stops after some time is know and is already logged in issue #191. The upcoming version will have a whole new audio subsystem which address that.

**Comment by LoveScanner** [comment]
> The first time you try to download, you should have been prompted to allow the storage permission to the app. It should ask again if you've answered deny. But on some android devices, you can also choose deny and do not ask again. If it's the case, you won't be prompted anymore and that could lead to the symptom you're describing. Go see in the app persmissions if it as storage permission or not; it should.
> 
> On android, calls are saved in the Download folder of the internal storage.
> 
> I have added a new error message to the upcoming version of the native app which will popup if the app doesn't have storage permission.
> 
> The audio issue where it stops after some time is know and is already logged in issue #191. The upcoming version will have a whole new audio subsystem which address that.

Permission enabled, I also tried to reinstall and confirmed again did not solve the problem - for information

**Comment by chuot** [comment]
Yes, please send the video with the details of your phone manufacturer, OS version and if the bootloader is still locked. My email is shown on my github profile.

**Comment by LoveScanner** [comment]
> Yes, please send the video with the details of your phone manufacturer, OS version and if the bootloader is still locked. My email is shown on my github profile.

Done.

**Comment by LoveScanner** [comment]
> Evereything looks good on your device.
> 
> Do you run the latest version of Rdio Scanner opensource (v6.4.4) ?

I had 6.4.2 now I updated to 6.4.4 - the issue was not resolved
If you want to diagnose a malfunction I have no problem sending you Anydesk remote access via mail

**Comment by chuot** [comment]
It looks like /storage/emulated/0/Download on your Note 10+ with oneUI 4.1. I'm working on it.

**Comment by chuot** [comment]
Ok, I found the issue where path.Base() doesn't work on Windows and should be replaced by filepath.Base().

It will be fixed in the next version.
