### ISSUE TITLE
 Permanent connection even in background work

### ISSUE THREAD

**Issue by LoveScanner** [chuot/rdio-scanner#219]
Permanent connection even in background work

One of the most notable drawbacks of the app is worth noting,
It does not always manage to maintain a permanent connection even when I am connected in WIFI and the communication itself is excellent,
Only when the app is open in front of the screen can a permanent and stable connection be ensured
It's worth thinking about how to improve a topic is a very significant drawback I'm sure not just for me.

Just for example - when using the "Zello PTT Walkie Talkie" broadcast application it always knows how to connect when the internet connection is down for a moment

**Comment by chuot** [comment]
native v1.8 has enhancement in that regards. It should be release on the main channel in a couple of hours.
