### ISSUE TITLE
Feature - Support Info

### ISSUE THREAD

**Issue by JayManCanada6014** [chuot/rdio-scanner#220]
Could we add a setting on the admin page that would let you place a URL or Email someplace on the website and app so people who need help can contact those of us running it?  I ask because you got one of my people looking for support so if we could tell people who to contact it may help with future issues.

**Comment by JayManCanada6014** [comment]
I like it all.

**Comment by chuot** [comment]
It's there since v6.5.0, so I guess I can close...
