### ISSUE TITLE
System duplicated upon restarting server

### ISSUE THREAD

**Issue by cpg178** [chuot/rdio-scanner#241]
I have noticed the last 2 times the machine running rdio-scanner reboots, or when I updated to 6.5.2 upon reboot a system named identical to one of mine, but with some extra talk groups is duplicated and takes up system id 2. The is that the systems that were previously ID 2 and 3 are bumped to 3 and 4 respectively, but new files being ingested sometimes do not recognize this change and get sent s to wrong place. This is easily fixed by deleting the errant system, but I'm confused as to why it keeps reappearing when I delete it and press save. 

This error has been appearing recently when changing the config, not sure if its related.
![image](https://user-images.githubusercontent.com/4503742/180206192-05c49496-76ce-417c-8e93-0cd5536db2b4.png)

**Comment by cpg178** [comment]
It appears after doing some research that even though I was removed the system from rdio-scanner, it was not removing it from the database.

**Comment by chuot** [comment]
Fixed in v6.5.3
