### ISSUE TITLE
Purging stopped

### ISSUE THREAD

**Issue by kb2ear** [chuot/rdio-scanner#256]
I have a number of systems running 6.5.2 and -db_type mysql that have not purged since between late June and early July. All purge times are set at the default of 7.

**Comment by chuot** [comment]
I can't help much without logs. Please provide some by attaching them to this issue.

**Comment by kb2ear** [comment]
I figured it out, the instances were restarting too often, I guess from when the instances would consume all the processor resources a few months back. Stopped the restart, purging now working as expected.
