### ISSUE TITLE
Searching by time is not accurate

### ISSUE THREAD

**Issue by cpg178** [chuot/rdio-scanner#258]
When using the time filter to find calls, it seems to be about an hour and 15 minutes behind on each search. i.e. if I want to find a call from 10am yesterday, in order to actually find it I need to put in 1115am, if i put in 10am it shows calls from around 8:45. See attached screenshot for an example 
![image](https://user-images.githubusercontent.com/4503742/187720475-0da9b36f-25d4-4478-abc2-080d407b0f54.png)

**Comment by chuot** [comment]
Confirmed as a bug. It happens when the sort order is set to descending.

**Comment by chuot** [comment]
@cpg178 Fixed with v6.5.4. Please confirm and close the issue.

**Comment by cpg178** [comment]
Works well now thanks for the quick fix!
