### ISSUE TITLE
Date in documentation for mask isn't clear

### ISSUE THREAD

**Issue by sjennison** [chuot/rdio-scanner#26]
The example date for mask, 2020-06-08, could be either June 8th, or August 6th... Perhaps use a day greater than 12 to make clear which value is day and which is month, or use the YYYY-MM-DD format?

**Comment by chuot** [comment]
Indeed it should be more clear. Will be fixed in the next coming release.

**Comment by chuot** [comment]
Fixed with v4.8.0
