### ISSUE TITLE
6.6.0 - Search Issue

### ISSUE THREAD

**Issue by JayManCanada6014** [chuot/rdio-scanner#267]
User reported this to me,  you will see a System and Talkgroup selected in the search below but the results are showing the entire system and not just the talkgroup results that were selected.

All Talk Groups:
![image](https://user-images.githubusercontent.com/66147998/194102717-ef15bd48-77ab-4c4f-8f06-6744987b0bf4.png)

One talk group selected:
![image](https://user-images.githubusercontent.com/66147998/194102793-deb8ac54-f4c9-4344-8d69-0cac7b066a39.png)

Results are the same.

**Comment by GitGoorilla** [comment]
I can confirm this. I'm having the same issue with the search feature. I rolled back and it works fine.

**Comment by atlex** [comment]
There is no search issue in 6.6.1 https://github.com/chuot/rdio-scanner/releases/tag/v6.6.1
Thank you @chuot

**Comment by JayManCanada6014** [comment]
Same,  6.6.1 resolves the issue.
