### ISSUE TITLE
Client Cookie To Save Selected Talkgroups

### ISSUE THREAD

**Issue by TheGreatCodeholio** [chuot/rdio-scanner#272]
Feature request, Have RDIO create a browser cookie that can save the state of selected talkgroups/systems or whatever is selected or not selected.

**Comment by chuot** [comment]
The selection of talkgroups is already stored on your browser's local storage. If you close your Rdio Scanner browser tab and reopen it, you should find all your talkgroups selection right where you left them. So no need for cookies.
