### ISSUE TITLE
Option to select buttons on homescreen

### ISSUE THREAD

**Issue by blackwellj** [chuot/rdio-scanner#274]
Would it be possible to allow the admin to select which buttons are shown on  the home screen? I run a single system that is purely conventional and have no use for at least 3 of the buttons. I would like to remove the unnecessary ones to save confusion

**Comment by chuot** [comment]
I'm surprised that at least 3 buttons are useless on your setup. IMO maybe HOLD SYS if you only have one system, but then you can split your conventional systems by region and make each region one system. Then HOLD SYS would be useful.

**Comment by blackwellj** [comment]
Avoid sys, avoid tg, skip next and avoid are not used on my system at all

James Blackwell

On 7 Nov 2022, at 11:22, Chrystian Huot ***@***.***> wrote:

﻿

I'm surprised that at least 3 buttons are useless on your setup. IMO maybe HOLD SYS if you only have one system, but then you can split your conventional systems by region and make each region one system. Then HOLD SYS would be useful.
