### ISSUE TITLE
screen information toggles

### ISSUE THREAD

**Issue by 8555726** [chuot/rdio-scanner#285]
Is it possible to have the frequency field toggled in settings, so it's not shown on the screen?

**Comment by chuot** [comment]
What is the reason for not displaying the frequency on which the conversation was picked up? The goal here is to reproduce a real police scanner.

**Comment by 8555726** [comment]
I'm mainly using it on an APCO23 trunking system but can see your point for conventional scanning

**Comment by chuot** [comment]
Well, I'm closing this as not planned. I do not wish to change the look and feel of the app. Ddisplaying the frequency is part of Rdio Scanner own identity.
