### ISSUE TITLE
Talkgroups Dissapear

### ISSUE THREAD

**Issue by hoffadg** [chuot/rdio-scanner#314]
After importing ~800 radioreference talkgroups and running for a while, sometimes all of the talkgroups for that system will eventually disappear.  I've seen it happen a few times over the last couple of weeks on on both the Windows and Linux version.

RDIO-Scanner V6.6.3

**Comment by chuot** [comment]
Is there any Rdio Scanner logs when that happens?

It happens once for a user where its database was corrupted. Again logs will help to troubleshoot.

**Comment by hoffadg** [comment]
> Is there any Rdio Scanner logs when that happens?
> 
> It happens once for a user where its database was corrupted. Again logs will help to troubleshoot.

I will grab the logs the next time it happens.  It hasn't happened in the last few weeks.

**Comment by chuot** [comment]
Closing since no new info on this.
