### ISSUE TITLE
cmd line util - error response 417

### ISSUE THREAD

**Issue by kcwebby** [chuot/rdio-scanner#325]
When using the cmd line tool to add/remove users, we have started to get a response of ``` 417 Expectation Failed
 ``` in lieu of the normal "XXXX user added"

**Comment by chuot** [comment]
By cmd line tool, I assume you're talking about the `rdio-scanner -cmd <command>` arguments passed to the Rdio Scanner executable. By looking at the code, there's something wrong while writing to the database. There must be some logs thrown by Rdio Scanner that could shed some light.

**Comment by chuot** [comment]
Closing as no new update on this issue
