### ISSUE TITLE
Downstream timing out

### ISSUE THREAD

**Issue by cpg178-kcd** [chuot/rdio-scanner#330]
Out of the blue I am constantly getting a "connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

I have rebooted the internet connection, and servers on both ends. It will successfully pass 1 file to the downstream but then everything else after fails. Nothing has changed on either device.

**Comment by cpg178-kcd** [comment]
Did some sniffing with wireshark and there is clear communication between both devices, but what is interesting is every packet appears to be UDP, whereas the error keeps saying "Dial TCP" and rarely "read TCP"

**Comment by cpg178-kcd** [comment]
![image](https://user-images.githubusercontent.com/78386731/221452613-36aace96-bab0-458d-b983-823a3ccd6d81.png)

**Comment by chuot** [comment]
The context expiration time is 30 seconds. This could be due to many factors such as a problematic proxy between the two, insufficient systems resources, problem with the network and so on.

More investigation is needed. Look at the system logs for something that could explain this.

**Comment by cpg178-kcd** [comment]
So interestingly enough after 4 hours of troubleshooting last night, I gave up for the evening and discovered this morning it is working fine. 

I will look deeper into any network issues, my initial suspicions was the limitations of SQLite trying to ingest multiple files from the very active trunking system along with multiple downstream coming in at the same time, but moving to MariaDB did not make any change.
