### ISSUE TITLE
Loss of audio when running Rdio in browser on android

### ISSUE THREAD

**Issue by Nirbles** [chuot/rdio-scanner#339]
Hello: I have an issue when I run rdio in a browser on my Samsung 23+, specifically the audio stops a short time after I start it and put my phone on my belt (no buttons are being pressed). The program is still running but the audio won't come back without refreshing. I have designated the browsers as never sleep and turned off battery saver settings I can find. Any ideas, or is their a way to run two systems in the app would be appreciated as a workaround. Thank you.

**Comment by chuot** [comment]
This may be because you have not enabled audio conversion on the server. Playing certain audio file formats may be problematic on some mobile devices. Audio conversion requires the FFMpeg software to be installed on the same host as the Rdio Scanner server. Make sure it is installed, then check the audio conversion option on the admin dashboard.

**Comment by Nirbles** [comment]
Thank you for reply. I checked...currently the setting is "enabled without normalization" should I change it?

**Comment by chuot** [comment]
No, you want it enabled. But is FFMpeg installed on the PC and does the PATH environment variable point to it?

If it's not installed, you should get a message saying "ffmpeg is not available, no audio conversion will be performed" when you start the server and when it first tries to convert an audio file.

If you are running Rdio Scanner on a Windows PC, I suggest you read the FAQ section on the PDF document that comes with the release. Unfortunately, installing FFMpeg on Windows isn't as easy as it is on a Linux machine.

**Comment by Nirbles** [comment]
I turned it off and on and saw no error message. I can also select with normalization or with loud normalization.

**Comment by Nirbles** [comment]
I verified FFMpeg is installed for Audacity. I do not see anything about this in the FAQ on page 19. How do I check the path environment?

**Comment by wmg819** [comment]
Start at step 12 here https://www.wikihow.com/Install-FFmpeg-on-Windows this link is from the rdio-scanner pdf (FAQ pg 20) and will show you how to check the environment path.

**Comment by Nirbles** [comment]
I followed all the steps and set the environment... when I run command I get:
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.

**Comment by wmg819** [comment]
First is this on a Windows system? If so do you have the ffmpeg folder on your C: drive or is it in another location or folder? When you open a command prompt and type ffmpeg -version does it list it? If your running a Linux Distro the set up would be different.

**Comment by Nirbles** [comment]
Yes Windows 11 and yes in C:\ drive
![bandicam 2023-03-25 14-12-06-289](https://user-images.githubusercontent.com/107197100/227734391-df250d05-d709-49ea-9280-583892e98570.jpg)
![bandicam 2023-03-25 14-12-22-576](https://user-images.githubusercontent.com/107197100/227734392-ba3b4139-b009-4dac-ab28-7f4f3475a6c2.jpg)
![bandicam 2023-03-25 14-12-22-576](https://user-images.githubusercontent.com/107197100/227734395-4e04d0c7-d09c-4923-b2d9-8c7b74e1ce95.jpg)
![bandicam 2023-03-25 14-12-06-289](https://user-images.githubusercontent.com/107197100/227734396-7562c96f-0d0a-4b4f-aee6-90a95a3598cf.jpg)

Please see attached screen shots...thank you.

**Comment by Nirbles** [comment]
Looks like it decided to work:
![bandicam 2023-03-25 14-26-31-828](https://user-images.githubusercontent.com/107197100/227735037-f31d2b76-55cd-45e3-90a0-973400a7404c.jpg)

**Comment by Nirbles** [comment]
now I just seen to set to rdio?

**Comment by wmg819** [comment]
Now all you should need to do is start rdio-scanner and go into the admin page, click on config then on options and set the conversion option you want. Once done the window cmd that rdio-scanner is running in should show the calls being ingested with the .m4a extension.

**Comment by Nirbles** [comment]
Thank you...is there any difference between With normal, without normal and/or with loud?

**Comment by wmg819** [comment]
For the 2 systems I monitor enabled without normalization seems to work well but I suggest you try each one to see how it sounds to you on your phone.

**Comment by Nirbles** [comment]
Success! (I will try the phone again)
![bandicam 2023-03-25 15-02-51-499](https://user-images.githubusercontent.com/107197100/227736470-80b81911-698b-4ca9-98b3-8a57c25c9026.jpg)
