### ISSUE TITLE
How to set up rdio on an iphone

### ISSUE THREAD

**Issue by ldentel05** [chuot/rdio-scanner#346]
I was recommended this app by a member at my company but I can’t seem to figure out how to set it up. He said he had to pay a fee to start. If someone would help me figure out how to get started that would be greatly appreciated.

**Comment by GitGoorilla** [comment]
This is front end software for the rdio-scanner server not something like the Scanner Radio app. For this, you would need access to a rdio-scanner back-end server or run your own. The app fee does not give you access to servers. It adds additional options and removes ads as far as I know.
