### ISSUE TITLE
Auto Play next call in Search Call

### ISSUE THREAD

**Issue by grahampaull** [chuot/rdio-scanner#384]
Hey, not sure if this is a bug or if I am missing a setting somewhere.

When I go to Search Calls and press play on a call that had taken place, it plays fine but does not jump to the next call.

I have seen this working a few times but can’t figure out how I done this.

This issue appears across mobile and desktop web and iOS app

**Comment by atlex** [comment]
Please set  the "Live Feed" button to red.

**Comment by grahampaull** [comment]
Aww, as simple as that.. can’t believe I missed that one.
