### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by mamamandy** [chuot/rdio-scanner#448]
Haven't been able to connect for three days. Yes I paid my bill! It says no link? I haven't changed anything! Not connected and No access code. Please help.

**Comment by chuot** [comment]
I think you are confusing the opensource project and some third party using this software and making money from it.

Can you tell what's in your server's url field?

**Comment by mamamandy** [comment]
https://664324173.rdio.alertpagesd   is all i can see in the app

**Comment by chuot** [comment]
Communicate directly with them. The GitHub space is only for the open source project. I am not linked to this company.
________________________________
De : mamamandy ***@***.***>
Envoyé : Tuesday, October 29, 2024 2:58:12 PM
À : chuot/rdio-scanner ***@***.***>
Cc : Chrystian Huot ***@***.***>; Comment ***@***.***>
Objet : Re: [chuot/rdio-scanner] Not connecting (Issue #448)


https://664324173.rdio.alertpagesd is all i can see in the app
