### ISSUE TITLE
Live feed playback stops after 3-4 minutes when running on PC (Firefox)

### ISSUE THREAD

**Issue by babooino** [chuot/rdio-scanner#5]
Live feed playback stops after 3-4 minutes when running on PC (Firefox) while archive update continues. After page reload and reactivating live feed mode playback resumes for next 3-4 minutes.

**Comment by chuot** [comment]
I tried to reproduce with Firefox on Windows, Linux and Android, but without success. It worked as planned for 60 minutes.

In Firefox, if you look at console.log (F12), do you see any error messages that might give us a hint?

Also, check on the server side if you see something wrong. Maybe you're running out of space?
