### ISSUE TITLE
Importing UIDs

### ISSUE THREAD

**Issue by Dewey3** [chuot/rdio-scanner#56]
Can comma separated UIDs (UID, UID Name) be added to the end of the talkgroups csv file for import using the newer administrative dashboard?  If so, what is the formatting?  Thank you.

**Comment by chuot** [comment]
Unfortunately it doesn't import UIDs at this time. I'm flaging this as an enhancement request. Thanks

**Comment by chuot** [comment]
Feature in v6.1
