### ISSUE TITLE
Search Calls Filter Drop Dows still filter after pressing reset button.

### ISSUE THREAD

**Issue by steve-horvath** [chuot/rdio-scanner#60]
Version:  Rdio Scanner 5.2.9, Docker installation

Interface:  Chrome version 94.0.4606.61, Firefox 91.0.2, and iOS app.

Issue:  When using the "Search Call", Filtering by a Group, then pressing the reset button, the Group drop down changes to "All Groups", however other drop-downs are filters to systems which have the previously selected group.

How to fix:  Go to the Groups drop, which will show all groups, select any group, and then select "All Groups".  System drop down will then show all systems.

**Comment by chuot** [comment]
A fix will be available in the upcoming v6.0

**Comment by chuot** [comment]
Fix in v6-beta branch
