### ISSUE TITLE
Feature request: Add a time to the Date picker on the "Search Call" page

### ISSUE THREAD

**Issue by atlex** [chuot/rdio-scanner#63]
Hi @chuot,

Thank you for great project!

It would be nice to choose a time of a call on the "Search Call" page.
I have about 12 000 calls per day. And i'm seek and tired to scroll to middle of a day.

<img width="1183" alt="Screen Shot 2021-11-16 at 10 01 23" src="https://user-images.githubusercontent.com/1758639/141936808-af8c202c-89d6-48b0-99b3-16e366ae5a7b.png">

**Comment by chuot** [comment]
Will try to fit this enhancement in the upcoming v6.0.
