### ISSUE TITLE
connect ENOENT 

### ISSUE THREAD

**Issue by jacygamer** [chuot/rdio-scanner#7]
Got rdio_scanner install and running when I try to upload talkgroups using mariadb 
.env
DB_HOST=localhost
DB_PORT=3306
DB_DIALECT=mariadb
DB_NAME=rdio_scanner
DB_USER=rdio_scanner
DB_PASS=password
DB_STORAGE=database.sqlite

NODE_ENV=production
NODE_HOST=localhost
NODE_PORT=3000

RDIO_APIKEYS=["*****"]
RDIO_PRUNEDAYS=7

I get "connect ENOENT password"
can someone tell me how to diagnose why

**Comment by chuot** [comment]
Try changing `DB_HOST=localhost` to `DB_HOST=127.0.0.1`. It looks like the `Sequelize` library cannot connect to your mariadb server.

Also, why are you using mariadb instead of the default sqlite dialect?

**Comment by jacygamer** [comment]
working changed to sqlite
