### ISSUE TITLE
talkgroup storage in v6-beta loses talkgroups

### ISSUE THREAD

**Issue by gisforgirard** [chuot/rdio-scanner#72]
talkgroups really should be in their own table, not stored in a json object inside a single table row...

try importing this system and watch the havoc that occurs...

the admin section becomes totally unusable and it refuses to save the talkgroups

[trs_tg_100.csv](https://github.com/chuot/rdio-scanner/files/7722904/trs_tg_100.csv)

**Comment by gisforgirard** [comment]
nevermind i have no idea what happened but wiping the entire tatabase and starting over at least made things work again

**Comment by gisforgirard** [comment]
SqlError: (conn=87, no: 1406, SQLState: 22001) Data too long for column 'talkgroups' at row 1
actually this explains a lot

**Comment by chuot** [comment]
I agree with you, talkgroups should reside in their own table. I will work that out for v6.1 which will come out somewhere in january. Thanks for reporting the issue.
