### ISSUE TITLE
Talkgroups are going missing on 6.1.1

### ISSUE THREAD

**Issue by JayManCanada6014** [chuot/rdio-scanner#77]
7am this morning I got told all my Ottawa EMS TGs are missing, restored my save config, they came back. I just checked again and they are all missing again.  There hasn't been a restart between them as well.

**Comment by JayManCanada6014** [comment]
Follow up;  It seems to be one system, if I open it on he admin screen to edit it, it shortly closes back up like the system was removed.  I tried to restore the config again, no luck and then I broke it. I deleted the system with the issues but then I crashed the entire thing.  Going to go back to 5.9 until resolved.

Also this is the crash message:  seems to be some of your coding from home in there still.

Jan 05 09:28:12 rdio-scanner rdio-scanner[1402636]: 2022/01/05 09:28:12 listeners count is 17
Jan 05 09:28:13 rdio-scanner rdio-scanner[1402636]: 2022/01/05 09:28:13 listeners count is 18
Jan 05 09:28:13 rdio-scanner rdio-scanner[1402636]: 2022/01/05 09:28:13 listeners count is 19
Jan 05 09:28:13 rdio-scanner rdio-scanner[1402636]: 2022/01/05 09:28:13 listeners count is 20
Jan 05 09:28:14 rdio-scanner rdio-scanner[1402636]: 2022/01/05 09:28:14 listeners count is 21
Jan 05 09:28:17 rdio-scanner rdio-scanner[1402636]: 2022/01/05 09:28:17 newcall: system=201 talkgroup=1506 file=1506-1641392888_867537500-call_83668.m4a success
Jan 05 09:28:17 rdio-scanner rdio-scanner[1402636]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 05 09:28:17 rdio-scanner rdio-scanner[1402636]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x96ef3f]
Jan 05 09:28:17 rdio-scanner rdio-scanner[1402636]: goroutine 36 [running]:
Jan 05 09:28:17 rdio-scanner rdio-scanner[1402636]: main.(*Controller).IngestCall(0xc000166000, 0xc0004167e0)
Jan 05 09:28:17 rdio-scanner rdio-scanner[1402636]:         /home/chuot/Dev/rdio-scanner/server/controller.go:318 +0xbff
Jan 05 09:28:17 rdio-scanner rdio-scanner[1402636]: main.(*Controller).Start.func2()
Jan 05 09:28:17 rdio-scanner rdio-scanner[1402636]:         /home/chuot/Dev/rdio-scanner/server/controller.go:617 +0xff
Jan 05 09:28:17 rdio-scanner rdio-scanner[1402636]: created by main.(*Controller).Start
Jan 05 09:28:17 rdio-scanner rdio-scanner[1402636]:         /home/chuot/Dev/rdio-scanner/server/controller.go:613 +0x2bb
Jan 05 09:28:17 rdio-scanner systemd[1]: rdio-scanner.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 05 09:28:17 rdio-scanner systemd[1]: rdio-scanner.service: Failed with result 'exit-code'.

**Comment by chuot** [comment]
It will be fix in 6.1.2. Please turn off autopopulate for now if you don't want it to crash until 6.1.2.

**Comment by JayManCanada6014** [comment]
I'm not sure that is it.  I wiped me DB, went into my backup config from v5, changed all the autopopulate from true to false.  Loaded it into v6.  And my entire EMS system is still showing, but calls are being tagged on the command line as no valid TG.

**Comment by chuot** [comment]
Can you send me by email a sample json file from your EMS system, plus a copy of your backup. I will try to reproduce.

**Comment by JayManCanada6014** [comment]
> Can you send me by email a sample json file from your EMS system, plus a copy of your backup. I will try to reproduce.

Done should be in your inbox soon.

**Comment by chuot** [comment]
Sigsegv is fix in v6.1.2, but I'm still tracking down your odd issue where talkgroups vanish from the config but just for your EMS system.
