### ISSUE TITLE
TG Patch Field Missing V6

### ISSUE THREAD

**Issue by JayManCanada6014** [chuot/rdio-scanner#82]
The talkgroup option for including other TG's as patches is missing in V6.

**Comment by chuot** [comment]
Indeed, it has been moved to the call object to allow livefeed to follow avoided talkgroups in a supergroup situation. See issue #65  for details.

**Comment by JayManCanada6014** [comment]
Ah ok, I don't think the patching system in trunk-recorder works as well as expected also isn't in past versions and I rolled mine back because of that P25 volume issue.
