### ISSUE TITLE
Android App does not queue DirWatch recordings.

### ISSUE THREAD

**Issue by Cole0209** [chuot/rdio-scanner#87]
I have a DirWatch setup from Trunking Recorder (Not Trunk-Recorder) for an EDACS system. On the website version the traffic will Queue and play just like it does for my Trunk-Recorder API systems, but on the android app it does not. I have to manually go into the Search Call option and click it for it to play. Once I do that it will play that transmission but will not auto play or queue any others. The screen indicates that I am not avoiding that TG when I manually play the call. 

I am on Rdio Scanner version 6.1.2

**Comment by Cole0209** [comment]
Sure thing sending you an email now

**Comment by JayManCanada6014** [comment]
And here I thought it was my other issues causing this. I am getting the same as well.

**Comment by Cole0209** [comment]
@JayManCanada6014 Should be fixed in 6.1.3
